import { calculateMargin, calculatePurchaseTotals } from '@/lib/admin/calculations';
import { presentationOptions } from '@/lib/admin/catalogs';
import type { InventoryMovement, Product, Purchase } from '@/lib/admin/types';

const now = new Date();

export const initialProducts: Product[] = [
  {
    id: 'prod-001',
    sku: 'TAC-PRED-314-001',
    name: 'Taco Predator 314-3',
    description: 'Taco profesional para jugadores avanzados con gran control de efecto.',
    category: 'tacos',
    subcategory: 'Fibra de carbono',
    brand: 'Predator',
    saleType: 'unit',
    unitMeasure: 'unidad',
    stockQuantity: 4,
    stockMinimum: 2,
    purchasePrice: 1650000,
    shippingCostAllocated: 80000,
    realUnitCost: 1730000,
    salePrice: 2390000,
    profitMargin: calculateMargin(1730000, 2390000),
    warehouseLocation: 'Vitrina A1',
    image: '/images/logo.png',
    status: 'active',
    purchasePresentation: 'unit',
    salePresentation: 'unit',
    conversionFactor: 1,
    presentations: [presentationOptions[0]],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'prod-002',
    sku: 'TIZ-TAOM-V10',
    name: 'Tiza Taom V10',
    description: 'Tiza premium de alta adherencia con baja suciedad.',
    category: 'tizas',
    subcategory: 'Caja de 12',
    brand: 'Taom',
    saleType: 'mixed',
    unitMeasure: 'unidad',
    stockQuantity: 36,
    stockMinimum: 18,
    purchasePrice: 18500,
    shippingCostAllocated: 1200,
    realUnitCost: 19700,
    salePrice: 32000,
    profitMargin: calculateMargin(19700, 32000),
    warehouseLocation: 'Estante B2',
    image: '/images/logo.png',
    status: 'active',
    purchasePresentation: 'box-12',
    salePresentation: 'unit',
    conversionFactor: 12,
    presentations: [presentationOptions[0], presentationOptions[2]],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'prod-003',
    sku: 'GUA-MOL-3D',
    name: 'Guante Molinari 3 Dedos',
    description: 'Guante comodo para deslizamiento uniforme en tacos de competencia.',
    category: 'guantes',
    subcategory: 'Por unidad',
    brand: 'Molinari',
    saleType: 'mixed',
    unitMeasure: 'unidad',
    stockQuantity: 9,
    stockMinimum: 10,
    purchasePrice: 22000,
    shippingCostAllocated: 1800,
    realUnitCost: 23800,
    salePrice: 39000,
    profitMargin: calculateMargin(23800, 39000),
    warehouseLocation: 'Estante C1',
    image: '/images/logo.png',
    status: 'active',
    purchasePresentation: 'dozen',
    salePresentation: 'unit',
    conversionFactor: 12,
    presentations: [presentationOptions[0], presentationOptions[1]],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'prod-004',
    sku: 'PAN-SIM-860',
    name: 'Pano Simonis 860',
    description: 'Pano profesional de mesa completa para pool de alto rendimiento.',
    category: 'panos-de-billar',
    subcategory: 'Mesa completa',
    brand: 'BillKing',
    saleType: 'unit',
    unitMeasure: 'unidad',
    stockQuantity: 2,
    stockMinimum: 1,
    purchasePrice: 560000,
    shippingCostAllocated: 45000,
    realUnitCost: 605000,
    salePrice: 850000,
    profitMargin: calculateMargin(605000, 850000),
    warehouseLocation: 'Bodega Textil',
    image: '/images/logo.png',
    status: 'active',
    purchasePresentation: 'unit',
    salePresentation: 'unit',
    conversionFactor: 1,
    presentations: [presentationOptions[0]],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'prod-005',
    sku: 'VIR-ABS-10',
    name: 'Virola ABS 10 mm',
    description: 'Virola de repuesto para restauracion de tacos.',
    category: 'virolas',
    subcategory: 'ABS',
    brand: 'Accesorios SPSM',
    saleType: 'unit',
    unitMeasure: 'unidad',
    stockQuantity: 0,
    stockMinimum: 8,
    purchasePrice: 2500,
    shippingCostAllocated: 300,
    realUnitCost: 2800,
    salePrice: 6000,
    profitMargin: calculateMargin(2800, 6000),
    warehouseLocation: 'Gaveta D4',
    image: '/images/logo.png',
    status: 'active',
    purchasePresentation: 'unit',
    salePresentation: 'unit',
    conversionFactor: 1,
    presentations: [presentationOptions[0]],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'prod-006',
    sku: 'EST-BK-24',
    name: 'Estuche BillKing 2x4',
    description: 'Estuche semirigido con compartimentos para tacos y extensiones.',
    category: 'estuches',
    subcategory: '2x4',
    brand: 'BillKing',
    saleType: 'unit',
    unitMeasure: 'unidad',
    stockQuantity: 7,
    stockMinimum: 3,
    purchasePrice: 165000,
    shippingCostAllocated: 12000,
    realUnitCost: 177000,
    salePrice: 295000,
    profitMargin: calculateMargin(177000, 295000),
    warehouseLocation: 'Vitrina B4',
    image: '/images/logo.png',
    status: 'active',
    purchasePresentation: 'unit',
    salePresentation: 'unit',
    conversionFactor: 1,
    presentations: [presentationOptions[0]],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
];

const taomPurchaseTotals = calculatePurchaseTotals(480000, 36000, 24);
const glovePurchaseTotals = calculatePurchaseTotals(180000, 12000, 12);

export const initialPurchases: Purchase[] = [
  {
    id: 'buy-001',
    productId: 'prod-002',
    supplier: 'Distribuciones Taom Latam',
    purchasedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    presentationQuantity: 2,
    quantityPurchased: 24,
    purchasePresentation: 'box-12',
    conversionFactor: 12,
    purchaseValueTotal: 480000,
    shippingValueTotal: 36000,
    totalInvestment: taomPurchaseTotals.totalInvestment,
    realUnitCost: taomPurchaseTotals.realUnitCost,
    suggestedSalePrice: 32000,
    estimatedMargin: calculateMargin(taomPurchaseTotals.realUnitCost, 32000),
  },
  {
    id: 'buy-002',
    productId: 'prod-003',
    supplier: 'Molinari Colombia',
    purchasedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    presentationQuantity: 1,
    quantityPurchased: 12,
    purchasePresentation: 'dozen',
    conversionFactor: 12,
    purchaseValueTotal: 180000,
    shippingValueTotal: 12000,
    totalInvestment: glovePurchaseTotals.totalInvestment,
    realUnitCost: glovePurchaseTotals.realUnitCost,
    suggestedSalePrice: 39000,
    estimatedMargin: calculateMargin(glovePurchaseTotals.realUnitCost, 39000),
  },
];

export const initialMovements: InventoryMovement[] = [
  {
    id: 'mov-001',
    productId: 'prod-002',
    type: 'purchase',
    reason: 'purchase',
    quantity: 24,
    notes: 'Reposicion de tizas premium',
    occurredAt: initialPurchases[0].purchasedAt,
    responsibleUser: 'Administrador',
    relatedUnitCost: initialPurchases[0].realUnitCost,
  },
  {
    id: 'mov-002',
    productId: 'prod-003',
    type: 'purchase',
    reason: 'purchase',
    quantity: 12,
    notes: 'Compra de guantes por docena',
    occurredAt: initialPurchases[1].purchasedAt,
    responsibleUser: 'Administrador',
    relatedUnitCost: initialPurchases[1].realUnitCost,
  },
  {
    id: 'mov-003',
    productId: 'prod-001',
    type: 'exit',
    reason: 'sale',
    quantity: 1,
    notes: 'Venta de taco profesional',
    occurredAt: new Date(now.getTime() - 1000 * 60 * 60 * 12).toISOString(),
    responsibleUser: 'Caja principal',
    relatedUnitCost: 1730000,
  },
  {
    id: 'mov-004',
    productId: 'prod-005',
    type: 'adjustment',
    reason: 'manual-adjustment',
    quantity: -2,
    notes: 'Ajuste por perdida de inventario',
    occurredAt: new Date(now.getTime() - 1000 * 60 * 60 * 6).toISOString(),
    responsibleUser: 'Administrador',
    relatedUnitCost: 2800,
  },
];
